trigger:
- main

pool: default

steps:
- script: echo "Starting Flutter installation"
  displayName: 'Install Flutter' 

- script: |
    git clone https://github.com/flutter/flutter.git -b stable
    export PATH="$PATH:`pwd`/flutter/bin"
    flutter precache
  displayName: 'Install Flutter and dependencies'

- script: flutter doctor
  displayName: 'Flutter Doctor'

- script: flutter test
  displayName: 'Run Flutter tests'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: './build'
    ArtifactName: 'drop'
    publishLocation: 'Container'
