name: Flutter CI for Dev

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.0' # Spécifiez la version de Flutter à utiliser

      - name: Install dependencies
        run: flutter pub get

      - name: Run flutter doctor
        run: flutter doctor

      - name: Analyze project source
        run: flutter analyze

      - name: Run tests
        run: flutter test
